name: Copy Knowledge Base to Graham Watts Web

on:
  push:
    # branches:
      # - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  copy-to-grahamwattsweb:
    runs-on: ubuntu-latest
    steps:
      - name: checkout KnowledgeBase
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Add Front Matter
        run: .github/scripts/addFrontMatter.sh
      - name: Update Links
        run: .github/scripts/updateLinks.sh
      - name: Convert H1 to H2
        run: .github/scripts/convertH1toH2.sh
      - name: "[DEBUG] Show file contents"
        run: github/scripts/printFileContents.sh
      # - name: Copy files to GrahamWattsWeb
      #   uses: nkoppel/push-files-to-another-repository@v1.1.2
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source-files: 'KnowledgeBase/*'
      #     destination-username: 'gingergraham'
      #     destination-repository: 'GrahamWattsWeb'
      #     destination-branch: 'main'
      #     destination-directory: 'src/_knowledge/'
      #     commit-email: '34165628+GingerGraham@users.noreply.github.com'
      #     commit-username: 'Graham Watts'
      #     commit-message: 'Copy from KnowledgeBase'

# source-files (argument)
# The files/directories to copy to the destination repository. Can have multiple space-separated filenames and globbing.

# destination-username (argument)
# The name of the user or organization which owns the destination repository. E.g. nkoppel

# destination-repository (argument)
# The name of the repository to copy files to, E.g. push-files-to-another-repository

# destination-branch (argument) [optional]
# The branch name for the destination repository. Defaults to master.

# destination-directory (argument) [optional]
# The directory in the destination repository to copy the source files into. Defaults to the destination project root.

# commit-username (argument) [optional]
# The username to use for the commit in the destination repository. Defaults to destination-username

# commit-email (argument)
# The email to use for the commit in the destination repository.

# commit-message (argument) [optional]
# The commit message to be used in the output repository. Defaults to "Update from [destination url]@[commit]".

# The string ORIGIN_COMMIT is replaced by [destination url]@[commit].

# API_TOKEN_GITHUB (environment)
# The github api token which allows this action to push to the destination repository. E.g.: API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
