on: 
  workflow_dispatch:

jobs:
  copy-to-web:
    runs-on: ubuntu-latest
    steps:
      - name: Push a file(s) to GrahamWattsWeb
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'Apple/'
          destination-username: 'gingergraham'
          destination-repository: 'GrahamWattsWeb'
          destination-branch: 'test'
          destination-directory: 'src/_pages/knowledge/'
          commit-email: '34165628+GingerGraham@users.noreply.github.com'
