on: 
  workflow_dispatch:

jobs:
  copy-to-web:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'Apple/* Development/*'
          destination-username: 'gingergraham'
          destination-repository: 'GrahamWattsWeb'
          destination-branch: 'test'
          destination-directory: 'src/_pages/knowledge/'
          commit-email: '34165628+GingerGraham@users.noreply.github.com'
